/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-17 05:45:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.domain.Basket;
import model.domain.User;
import model.domain.Calculate;
import java.util.ArrayList;
import java.util.HashMap;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1609133365586L));
    _jspx_dependants.put("jar:file:/C:/ITStudy/04.Web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShoppingProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.domain.User");
    _jspx_imports_classes.add("model.domain.Calculate");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("model.domain.Basket");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Product List</title>\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- Place favicon.ico in the root directory -->\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"images/favicon.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- All css files are included here. -->\r\n");
      out.write("<!-- Bootstrap fremwork main css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<!-- Owl Carousel main css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("<!-- This core.css file contents all plugings css file. -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/core.css\">\r\n");
      out.write("<!-- Theme shortcodes/elements style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/shortcode/shortcodes.css\">\r\n");
      out.write("<!-- Theme main style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<!-- Responsive css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("<!-- User style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("<!--  Axios -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js\"></script>\r\n");
      out.write("<!-- Modernizr JS -->\r\n");
      out.write("<script src=\"js/vendor/modernizr-2.8.3.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--[if lt IE 8]>\r\n");
      out.write("        <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Body main wrapper start -->\r\n");
      out.write("\t<div class=\"wrapper fixed__footer\">\r\n");
      out.write("\t\t<!-- Start Header Style -->\r\n");
      out.write("\t\t<header id=\"header\" class=\"htc-header header--3 bg__white\">\r\n");
      out.write("\t\t\t<!-- Start Mainmenu Area -->\r\n");
      out.write("\t\t\t<div id=\"sticky-header-with-topbar\"\r\n");
      out.write("\t\t\t\tclass=\"mainmenu__area sticky__header\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-lg-2 col-sm-3 col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"index.html\"> <img src=\"images/logo/logo.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Start MAinmenu Ares -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8 col-lg-8 col-sm-6 col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<nav class=\"mainmenu__nav hidden-xs hidden-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"main__menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"shop.jsp\">Shop</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"about.html\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mobile-menu clearfix visible-xs visible-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<nav id=\"mobile_dropdown\" style=\"display: block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"shop.jsp\">Shop</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"about.html\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- End MAinmenu Ares -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-4 col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"menu-extra\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"search search__open hidden-xs\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"ti-search\"></span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"login-register.jsp\"><span class=\"ti-user\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"cart__menu\" onclick=\"ajaxCart()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"ti-shopping-cart\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"toggle__menu hidden-xs hidden-sm\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"ti-menu\" style=\"display: none;\"></span></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"mobile-menu-area\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End Mainmenu Area -->\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<!-- End Header Style -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"body__overlay\"></div>\r\n");
      out.write("\t\t<!-- Start Offset Wrapper -->\r\n");
      out.write("\t\t<div class=\"offset__wrapper\">\r\n");
      out.write("\t\t\t<!-- Start Search Popap -->\r\n");
      out.write("\t\t\t<div class=\"search__area\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"search__inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"#\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input placeholder=\"Search here... \" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"search__close__btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"search__close__btn_icon\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"zmdi zmdi-close\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End Search Popap -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Start Cart Panel -->\r\n");
      out.write("\t\t\t<div class=\"shopping__cart\">\r\n");
      out.write("\t\t\t\t<div class=\"shopping__cart__inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"offsetmenu__close__btn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"zmdi zmdi-close\"></i></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"ajaxcart\"></div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"shopping__btn\">\r\n");
      out.write("\t\t\t\t\t\t<li><a Onclick=\"location.href='Controller?command=getBasket'\">View\r\n");
      out.write("\t\t\t\t\t\t\t\tCart</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"shp__checkout\"><a\r\n");
      out.write("\t\t\t\t\t\t\tOnclick=\"location.href='Controller?command=buyBasket'\">Checkout</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End Cart Panel -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("   \t\t<script>               \r\n");
      out.write("\tfunction ajaxCart(){\r\n");
      out.write("\t   axios.get('responseBasket.jsp')\r\n");
      out.write("\t  .then(function (response) { \r\n");
      out.write("\t\tconsole.log(\"성공\");\r\n");
      out.write("\t\tdocument.getElementById(\"ajaxcart\").innerHTML = response.data;\r\n");
      out.write("\t  })\r\n");
      out.write("\t  .catch(function (error) { \r\n");
      out.write("\t    console.log(error);\r\n");
      out.write("\t  })\r\n");
      out.write("\t  .then(function () {\r\n");
      out.write("\t    // always executed\r\n");
      out.write("\t  });\r\n");
      out.write("\t} \r\n");
      out.write("   </script>\r\n");
      out.write("\t\t<!-- End Offset Wrapper -->\r\n");
      out.write("\t\t<!-- Start Bradcaump area -->\r\n");
      out.write("\t\t<div class=\"ht__bradcaump__area\"\r\n");
      out.write("\t\t\tstyle=\"background: rgba(0, 0, 0, 0) url(images/bg/2.jpg) no-repeat scroll center center/cover;\">\r\n");
      out.write("\t\t\t<div class=\"ht__bradcaump__wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bradcaump__inner text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"bradcaump-title\">Hello, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<nav class=\"bradcaump-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"breadcrumb-item\" href=\"index.html\">Home</a> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"brd-separetor\">/</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"breadcrumb-item active\">Checkout</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End Bradcaump area -->\r\n");
      out.write("\t\t<!-- cart-main-area start -->\r\n");
      out.write("\t\t<div class=\"cart-main-area ptb--120 bg__white\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"table-content table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"Basket ID\">Basket ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"User Name\">User Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"Product ID\">Product ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"Product Count\">Product Count</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"product-subtotal\">Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar totalCount = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar totalPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-8 col-sm-7 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"buttons-cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"shop.jsp\">Continue Shopping</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4 col-sm-5 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"cart_totals\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h2>Cart Totals</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"order-total\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Total Count</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><div id=\"tc\"></div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"order-total\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Total Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"tp\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"tc\").innerHTML = totalCount;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"tp\").innerHTML = totalPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-lg-8\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ckeckout-left-sidebar\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Start Checkbox Area -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"checkout-form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"section-title-3\">Pay Form</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"checkout-form-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"Controller\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"single-checkout-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"address\" size=\"24\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired=\"required\" placeholder=\"Address\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"single-checkout-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"contact\" size=\"24\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired=\"required\" placeholder=\"Contact\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"single-checkout-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"ccNumber\" size=\"24\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired=\"required\" placeholder=\"Credit Card Number\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"single-checkout-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"ccExpiration\" size=\"24\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired=\"required\" placeholder=\"Credit Card Expiration\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"single-checkout-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"ccPassword\" size=\"24\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired=\"required\" placeholder=\"Credit Card Password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"userId\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"command\" value=\"payBasket\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Confirm & Buy Now\">&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"reset\" value=\"reset\">&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- End Checkbox Area -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Start Payment Way -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"our-payment-sestem\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"section-title-3\">We Accept :</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"payment-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/payment/1.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\talt=\"payment-img\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/payment/2.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\talt=\"payment-img\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/payment/3.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\talt=\"payment-img\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/payment/4.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\talt=\"payment-img\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/payment/5.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\talt=\"payment-img\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- End Payment Way -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"checkout-right-sidebar\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"our-important-note\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"section-title-3\">Note :</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"note-desc\">Take caution as we provide no refunds.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"important-note\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"zmdi zmdi-caret-right-circle\"></i>All sales are final.</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"zmdi zmdi-caret-right-circle\"></i>No returns accepted.</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"zmdi zmdi-caret-right-circle\"></i>Good products\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tguaranteed.</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"puick-contact-area mt--60\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"section-title-3\">Contact Us</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>02-123-4567</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- cart-main-area end -->\r\n");
      out.write("\t\t<!-- Start Footer Area -->\r\n");
      out.write("\t\t<footer class=\"htc__foooter__area gray-bg\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"footer__container clearfix\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Start Single Footer Widget -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-lg-3 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ft__widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ft__logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"index.html\"> <img src=\"images/logo/logo.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"footer logo\" style=\"max-width: 80%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer-address\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"address-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"zmdi zmdi-pin\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"address-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Seoul, South Korea</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"address-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"zmdi zmdi-email\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"address-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"> info@example.com</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"address-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"zmdi zmdi-phone-in-talk\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"address-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>02-123-4567</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- End Single Footer Widget -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-lg-2 col-sm-6 smt-30 xmt-30\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ft__widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"ft__title\">Infomation</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"footer-categories\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Start Copyright Area -->\r\n");
      out.write("\t\t\t\t<div class=\"htc__copyright__area\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12 col-lg-12 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"copyright__inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>© 2020 TECHNOLOGI All Rights Reserved.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"footer__menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"shop.jsp\">Product</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- End Copyright Area -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t<!-- End Footer Area -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Body main wrapper end -->\r\n");
      out.write("\t<!-- Placed js at the end of the document so the pages load faster -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- jquery latest version -->\r\n");
      out.write("\t<script src=\"js/vendor/jquery-1.12.0.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap framework js -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- All js plugins included in this file. -->\r\n");
      out.write("\t<script src=\"js/plugins.js\"></script>\r\n");
      out.write("\t<script src=\"js/slick.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<!-- Waypoints.min.js. -->\r\n");
      out.write("\t<script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Main js file that contents all jQuery plugins activation. -->\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /checkout.jsp(208,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/checkout.jsp(208,10) '${sessionScope.baskets}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.baskets}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /checkout.jsp(208,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("data");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"Basket ID\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.basketId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"User Name\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"Product ID\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"Product Count\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.productCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"product-subtotal\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.prices.get(data.productId)*data.productCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t totalCount += parseInt(`");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.productCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("`);\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t totalPrice += parseInt(`");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.prices.get(data.productId)*data.productCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("`); \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t </script>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
