/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-17 05:46:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.domain.User;
import model.domain.Product;
import model.Service;
import java.util.ArrayList;
import java.util.HashMap;

public final class shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1609133365586L));
    _jspx_dependants.put("jar:file:/C:/ITStudy/04.Web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShoppingProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Service");
    _jspx_imports_classes.add("model.domain.User");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("model.domain.Product");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Shop</title>\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- Place favicon.ico in the root directory -->\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"images/favicon.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- All css files are included here. -->\r\n");
      out.write("<!-- Bootstrap fremwork main css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<!-- Owl Carousel main css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("<!-- This core.css file contents all plugings css file. -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/core.css\">\r\n");
      out.write("<!-- Theme shortcodes/elements style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/shortcode/shortcodes.css\">\r\n");
      out.write("<!-- Theme main style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<!-- Responsive css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("<!-- User style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("<!--  Axios -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js\"></script>\r\n");
      out.write("<!-- Modernizr JS -->\r\n");
      out.write("<script src=\"js/vendor/modernizr-2.8.3.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--[if lt IE 8]>\r\n");
      out.write("        <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Body main wrapper start -->\r\n");
      out.write("\t<div class=\"wrapper fixed__footer\">\r\n");
      out.write("\t\t<!-- Start Header Style -->\r\n");
      out.write("\t\t<header id=\"header\" class=\"htc-header header--3 bg__white\">\r\n");
      out.write("\t\t\t<!-- Start Mainmenu Area -->\r\n");
      out.write("\t\t\t<div id=\"sticky-header-with-topbar\"\r\n");
      out.write("\t\t\t\tclass=\"mainmenu__area sticky__header\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-lg-2 col-sm-3 col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"index.html\"> <img src=\"images/logo/logo.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Start MAinmenu Ares -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8 col-lg-8 col-sm-6 col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<nav class=\"mainmenu__nav hidden-xs hidden-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"main__menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"shop.jsp\">Shop</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"about.html\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mobile-menu clearfix visible-xs visible-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<nav id=\"mobile_dropdown\" style=\"display: block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"shop.jsp\">Shop</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"about.html\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- End MAinmenu Ares -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-4 col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"menu-extra\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"search search__open hidden-xs\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"ti-search\"></span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"login-register.jsp\"><span class=\"ti-user\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"cart__menu\" onclick=\"ajaxCart()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"ti-shopping-cart\"></span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"toggle__menu hidden-xs hidden-sm\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"ti-menu\" style=\"display: none;\"></span></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"mobile-menu-area\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End Mainmenu Area -->\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<!-- End Header Style -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"body__overlay\"></div>\r\n");
      out.write("\t\t<!-- Start Offset Wrapper -->\r\n");
      out.write("\t\t<div class=\"offset__wrapper\">\r\n");
      out.write("\t\t\t<!-- Start Search Popap -->\r\n");
      out.write("\t\t\t<div class=\"search__area\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"search__inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"#\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input placeholder=\"Search here... \" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"search__close__btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"search__close__btn_icon\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"zmdi zmdi-close\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End Search Popap -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Start Cart Panel -->\r\n");
      out.write("\t\t\t<div class=\"shopping__cart\">\r\n");
      out.write("\t\t\t\t<div class=\"shopping__cart__inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"offsetmenu__close__btn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"zmdi zmdi-close\"></i></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"ajaxcart\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"shopping__btn\">\r\n");
      out.write("\t\t\t\t\t\t<li><a Onclick=\"location.href='Controller?command=getBasket'\">View\r\n");
      out.write("\t\t\t\t\t\t\t\tCart</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"shp__checkout\"><a\r\n");
      out.write("\t\t\t\t\t\t\tOnclick=\"location.href='Controller?command=buyBasket'\">Checkout</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End Cart Panel -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<script>               \r\n");
      out.write("\tfunction ajaxCart(){\r\n");
      out.write("\t   axios.get('responseBasket.jsp')\r\n");
      out.write("\t  .then(function (response) { \r\n");
      out.write("\t\tconsole.log(\"성공\");\r\n");
      out.write("\t\tdocument.getElementById(\"ajaxcart\").innerHTML = response.data;\r\n");
      out.write("\t  })\r\n");
      out.write("\t  .catch(function (error) { \r\n");
      out.write("\t    console.log(error);\r\n");
      out.write("\t  })\r\n");
      out.write("\t  .then(function () {\r\n");
      out.write("\t    // always executed\r\n");
      out.write("\t  });\r\n");
      out.write("\t} \r\n");
      out.write("   </script>\r\n");
      out.write("\t\t<!-- End Offset Wrapper -->\r\n");
      out.write("\t\t<!-- Start Bradcaump area -->\r\n");
      out.write("\t\t<div class=\"ht__bradcaump__area\"\r\n");
      out.write("\t\t\tstyle=\"background: rgba(0, 0, 0, 0) url(images/bg/2.jpg) no-repeat scroll center center/cover;\">\r\n");
      out.write("\t\t\t<div class=\"ht__bradcaump__wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bradcaump__inner text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"bradcaump-title\">Hello, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<nav class=\"bradcaump-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"breadcrumb-item\" href=\"index.html\">Home</a> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"brd-separetor\">/</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"breadcrumb-item active\">Shop Page</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End Bradcaump area -->\r\n");
      out.write("\t\t<!-- Start Our Product Area -->\r\n");
      out.write("\t\t<section class=\"htc__product__area shop__page ptb--130 bg__white\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"htc__product__container\">\r\n");
      out.write("\t\t\t\t\t<!-- Start Product MEnu -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"filter__menu__container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product__menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button data-filter=\"*\" class=\"is-checked\">All\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tProducts</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Start Filter Menu -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- End Filter Menu -->\r\n");
      out.write("\t\t\t\t\t<!-- End Product Menu -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product__list another-product-style\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!-- End Our Product Area -->\r\n");
      out.write("\t\t<!-- Start Footer Area -->\r\n");
      out.write("\t\t<footer class=\"htc__foooter__area gray-bg\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"footer__container clearfix\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Start Single Footer Widget -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-lg-3 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ft__widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ft__logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"index.html\"> <img src=\"images/logo/logo.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"footer logo\" style=\"max-width: 80%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer-address\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"address-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"zmdi zmdi-pin\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"address-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Seoul, South Korea</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"address-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"zmdi zmdi-email\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"address-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"> info@example.com</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"address-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"zmdi zmdi-phone-in-talk\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"address-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>02-123-4567</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- End Single Footer Widget -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-lg-2 col-sm-6 smt-30 xmt-30\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ft__widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"ft__title\">Infomation</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"footer-categories\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Start Copyright Area -->\r\n");
      out.write("\t\t\t\t<div class=\"htc__copyright__area\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12 col-lg-12 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"copyright__inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>© 2020 TECHNOLOGI All Rights Reserved.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"footer__menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"shop.jsp\">Product</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- End Copyright Area -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t<!-- End Footer Area -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Body main wrapper end -->\r\n");
      out.write("\t<!-- QUICKVIEW PRODUCT -->\r\n");
      out.write("\t<div id=\"quickview-wrapper\">\r\n");
      out.write("\t\t<!-- Modal -->\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<!-- END Modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END QUICKVIEW PRODUCT -->\r\n");
      out.write("\t<!-- Placed js at the end of the document so the pages load faster -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- jquery latest version -->\r\n");
      out.write("\t<script src=\"js/vendor/jquery-1.12.0.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap framework js -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- All js plugins included in this file. -->\r\n");
      out.write("\t<script src=\"js/plugins.js\"></script>\r\n");
      out.write("\t<script src=\"js/slick.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<!-- Waypoints.min.js. -->\r\n");
      out.write("\t<script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Main js file that contents all jQuery plugins activation. -->\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /shop.jsp(205,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/shop.jsp(205,7) '${sessionScope.products}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.products}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /shop.jsp(205,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("pro");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<!-- Start Single Product -->\r\n");
            out.write("\t\t\t\t\t\t\t\t<div\r\n");
            out.write("\t\t\t\t\t\t\t\t\tclass=\"col-md-3 single__pro col-lg-3 cat--1 col-sm-4 col-xs-12\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"product foo\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product__inner\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"pro__thumb\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
            out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<img src=\"images/product/big-img/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".jpg\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"product__hover__info\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"product__action\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a data-toggle=\"modal\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#productModal");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttitle=\"Quick View\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"quick-view modal-view detail-link\" href=\"#\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t <span class=\"ti-plus\"></span>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product__details\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<h2>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product-details.html\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</h2>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"product__price\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"old__price\">$");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.price*1.2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"new__price\">$");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t<!-- End Single Product -->\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /shop.jsp(333,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/shop.jsp(333,2) '${sessionScope.products}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.products}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /shop.jsp(333,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("pro");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t<div class=\"modal fade\" id=\"productModal");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("\t\t\t\ttabindex=\"-1\" role=\"dialog\">\r\n");
            out.write("\t\t\t\t<div class=\"modal-dialog modal__container\" role=\"document\">\r\n");
            out.write("\t\t\t\t\t<div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
            out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
            out.write("\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
            out.write("\t\t\t\t\t\t\t</button>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t<!--  -->\r\n");
            out.write("\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"modal-product\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<!-- Start product images -->\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"product-images\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"main-image images\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/product/big-img/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".jpg\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t<!-- end product images -->\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"product-info\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<h1>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h1>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<h3>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.productType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h3>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"price-box-3\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"s-price-box\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"new-price\">$");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span> <span\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"old-price\">$");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.price*1.2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"quick-desc\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" Type:\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.productType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" Available: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.inventory}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"addtocart-btn\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<form action=\"Controller\" method=\"post\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\tEnter Quantity : <input type=\"hidden\" name=\"productId\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> <input type=\"text\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"productCount\"> <input type=\"hidden\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"command\" value=\"addBasket\"> <input\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"submit\" value=\"Take\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t<!-- .product-info -->\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t<!-- .modal-product -->\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t<!-- .modal-body -->\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t<!-- .modal-content -->\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t<!-- .modal-dialog -->\r\n");
            out.write("\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
