/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-16 15:01:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Iterator");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Update Product</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"images/favicon.ico\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- All css files are included here. -->\r\n");
      out.write("    <!-- Bootstrap fremwork main css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <!-- This core.css file contents all plugings css file. -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/core.css\">\r\n");
      out.write("    <!-- Theme shortcodes/elements style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/shortcode/shortcodes.css\">\r\n");
      out.write("    <!-- Theme main style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <!-- Responsive css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("    <!-- User style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Modernizr JS -->\r\n");
      out.write("    <script src=\"js/vendor/modernizr-2.8.3.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!--[if lt IE 8]>\r\n");
      out.write("        <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\r\n");
      out.write("    <![endif]-->  \r\n");
      out.write("\r\n");
      out.write("    <!-- Body main wrapper start -->\r\n");
      out.write("    <div class=\"wrapper fixed__footer\">\r\n");
      out.write("          <!-- Start Header Style -->\r\n");
      out.write("        <header id=\"header\" class=\"htc-header header--3 bg__white\">\r\n");
      out.write("            <!-- Start Mainmenu Area -->\r\n");
      out.write("            <div id=\"sticky-header-with-topbar\" class=\"mainmenu__area sticky__header\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-2 col-lg-2 col-sm-3 col-xs-3\">\r\n");
      out.write("                            <div class=\"logo\">\r\n");
      out.write("                                <a href=\"index.html\">\r\n");
      out.write("                                    <img src=\"images/logo/logo.png\" alt=\"logo\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Start MAinmenu Ares -->\r\n");
      out.write("                        <div class=\"col-md-8 col-lg-8 col-sm-6 col-xs-6\">\r\n");
      out.write("                            <nav class=\"mainmenu__nav hidden-xs hidden-sm\">\r\n");
      out.write("                                <ul class=\"main__menu\">\r\n");
      out.write("                                    <li class=\"drop\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                    <li class=\"drop\"><a href=\"shop.jsp\">Shop</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"drop\"><a href=\"about.html\">About</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </nav>\r\n");
      out.write("                            <div class=\"mobile-menu clearfix visible-xs visible-sm\">\r\n");
      out.write("                                <nav id=\"mobile_dropdown\" style=\"display: block;\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                        <li class=\"drop\"><a href=\"shop.jsp\">Shop</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"drop\"><a href=\"about.html\">About</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                        <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>                          \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- End MAinmenu Ares -->\r\n");
      out.write("                        <div class=\"col-md-2 col-sm-4 col-xs-3\">  \r\n");
      out.write("                            <ul class=\"menu-extra\">\r\n");
      out.write("                                <li class=\"search search__open hidden-xs\"><span class=\"ti-search\"></span></li>\r\n");
      out.write("                                <li><a href=\"login-register.jsp\"><span class=\"ti-user\"></span></a></li>\r\n");
      out.write("                                <li class=\"cart__menu\"><span class=\"ti-shopping-cart\" style=\"display:none;\"></span></li>\r\n");
      out.write("                                <li class=\"toggle__menu hidden-xs hidden-sm\"><span class=\"ti-menu\" style = \"display:none;\"></span></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mobile-menu-area\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Mainmenu Area -->\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- End Header Style -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"body__overlay\"></div>\r\n");
      out.write("        <!-- Start Offset Wrapper -->\r\n");
      out.write("        <div class=\"offset__wrapper\">\r\n");
      out.write("            <!-- Start Search Popap -->\r\n");
      out.write("            <div class=\"search__area\">\r\n");
      out.write("                <div class=\"container\" >\r\n");
      out.write("                    <div class=\"row\" >\r\n");
      out.write("                        <div class=\"col-md-12\" >\r\n");
      out.write("                            <div class=\"search__inner\">\r\n");
      out.write("                                <form action=\"#\" method=\"get\">\r\n");
      out.write("                                    <input placeholder=\"Search here... \" type=\"text\">\r\n");
      out.write("                                    <button type=\"submit\"></button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                                <div class=\"search__close__btn\">\r\n");
      out.write("                                    <span class=\"search__close__btn_icon\"><i class=\"zmdi zmdi-close\"></i></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Search Popap -->     \r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Offset Wrapper -->\r\n");
      out.write("        <!-- Start Login Register Area -->\r\n");
      out.write("        <div class=\"htc__login__register bg__white ptb--130\" style=\"background: rgba(0, 0, 0, 0) url(images/bg/5.jpg) no-repeat scroll center center / cover ;\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("                        <ul class=\"login__register__menu\" role=\"tablist\">\r\n");
      out.write("                            <li role=\"presentation\" class=\"login active\"><a href=\"#login\" role=\"tab\" data-toggle=\"tab\">Update Product</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Start Login Register Content -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("                        <div class=\"htc__login__register__wrap\">\r\n");
      out.write("                            <!-- Start Single Content -->\r\n");
      out.write("                            <div id=\"login\" role=\"tabpanel\" class=\"single__tabs__panel tab-pane fade in active\">\r\n");
      out.write("                               <form class=\"login\" action = \"Controller\" method=\"post\">\r\n");
      out.write("                                \t<input type=\"text\"  name=\"productId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.product.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("                                    <input type=\"text\"  name=\"producttype\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.product.productType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"productname\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.product.productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"description\" placeholder=\"Description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"price\" placeholder=\"Price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"inventory\" placeholder=\"Inventory\">\r\n");
      out.write("           \t\t\t\t\t\t\t<input type=\"hidden\" name=\"command\" value=\"updateProduct\">\r\n");
      out.write("                              \r\n");
      out.write("                               \r\n");
      out.write("                                <div class=\"htc__login__btn\">\r\n");
      out.write("                                     <input type=\"submit\" value=\"Update Product\">\r\n");
      out.write("            \t\t\t\t\t\t <input type=\"reset\" value=\"Reset\">&nbsp;&nbsp;\r\n");
      out.write("                                </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End Single Content -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End Login Register Content -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Login Register Area -->\r\n");
      out.write("              <!-- Start Footer Area -->\r\n");
      out.write("        <footer class=\"htc__foooter__area gray-bg\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"footer__container clearfix\">\r\n");
      out.write("                         <!-- Start Single Footer Widget -->\r\n");
      out.write("                        <div class=\"col-md-3 col-lg-3 col-sm-6\">\r\n");
      out.write("                            <div class=\"ft__widget\">\r\n");
      out.write("                                <div class=\"ft__logo\">\r\n");
      out.write("                                    <a href=\"index.html\">\r\n");
      out.write("                                        <img src=\"images/logo/logo.png\" alt=\"footer logo\" style=\"max-width: 80%;\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"footer-address\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"address-icon\">\r\n");
      out.write("                                                <i class=\"zmdi zmdi-pin\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"address-text\">\r\n");
      out.write("                                                <p>Seoul, South Korea</p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"address-icon\">\r\n");
      out.write("                                                <i class=\"zmdi zmdi-email\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"address-text\">\r\n");
      out.write("                                                <a href=\"#\"> info@example.com</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"address-icon\">\r\n");
      out.write("                                                <i class=\"zmdi zmdi-phone-in-talk\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"address-text\">\r\n");
      out.write("                                                <p>02-123-4567</p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- End Single Footer Widget -->\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-md-3 col-lg-2 col-sm-6 smt-30 xmt-30\">\r\n");
      out.write("                            <div class=\"ft__widget\">\r\n");
      out.write("                                <h2 class=\"ft__title\">Infomation</h2>\r\n");
      out.write("                                <ul class=\"footer-categories\">\r\n");
      out.write("                                    <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("                                    <li><a href=\"contact.html\">Contact Us</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Start Copyright Area -->\r\n");
      out.write("                <div class=\"htc__copyright__area\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12 col-lg-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                            <div class=\"copyright__inner\">\r\n");
      out.write("                                <div class=\"copyright\">\r\n");
      out.write("                                    <p>© 2020 TECHNOLOGI \r\n");
      out.write("                                    All Rights Reserved.</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <ul class=\"footer__menu\">\r\n");
      out.write("                                    <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                    <li><a href=\"shop.jsp\">Product</a></li>\r\n");
      out.write("                                    <li><a href=\"contact.html\">Contact Us</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End Copyright Area -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- End Footer Area -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Body main wrapper end -->\r\n");
      out.write("    <!-- Placed js at the end of the document so the pages load faster -->\r\n");
      out.write("\r\n");
      out.write("    <!-- jquery latest version -->\r\n");
      out.write("    <script src=\"js/vendor/jquery-1.12.0.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap framework js -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- All js plugins included in this file. -->\r\n");
      out.write("    <script src=\"js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"js/slick.min.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <!-- Waypoints.min.js. -->\r\n");
      out.write("    <script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("    <!-- Main js file that contents all jQuery plugins activation. -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
